//Player Actions
export const CONNECT_SOCKET_IO_PLAYER="CONNECT_SOCKET_IO_PLAYER"
export const CLICK_SUBMIT_PIN = "CLICK_SUBMIT_PIN";
export const IS_JOIN_ROOM = "IS_JOIN_ROOM";
export const IS_PLAY = "IS_PLAY";
export const LOAD_QUESTIONS = "LOAD_QUESTIONS";
export const LOAD_QUESTION = "LOAD_QUESTION";
export const CLICK_ANSWER = "CLICK_ANSWER";
export const SET_TIME_QUESTION_PLAYER = "SET_TIME_QUESTION_PLAYER";
export const SAVE_NEW_MEMBER_PLAYER = "SAVE_NEW_MEMBER_PLAYER";
export const PLAYER_CLICK_BUTTON_ANSWER = "PLAYER_CLICK_BUTTON_ANSWER";
export const SET_SCORE_PLAYER = "SET_SCORE_PLAYER";
//Host Actions
export const CONNECT_SOCKET_IO_HOST="CONNECT_SOCKET_IO_HOST"
export const GET_QUESTION="GET_QUESTION"
export const SAVE_NEW_MEMBER = "SAVE_NEW_MEMBER";
export const MEMBER_BEFORE_TIME_OUT = "MEMBER_BEFORE_TIME_OUT";
export const CLICK_START_PLAY = "CLICK_START_PLAY";
export const CLICK_NEXT_QUESTION = "CLICK_NEXT_QUESTION";
export const MEMBER_EXIT = "MEMBER_EXIT";
export const MEMBER_ANSWER = "MEMBER_ANSWER";
export const SET_TIME_QUESTION_HOST = "SET_TIME_QUESTION_HOST";
//Login Actions
export const ON_CHANGE_LOGIN = "ON_CHANGE_LOGIN";
//Register Actions
export const ON_CHANGE_REGISTER = "ON_CHANGE_REGISTER";
//Home Actions
export const SAVE_INFO_USER = "SAVE_INFO_USER";
export const SAVE_QUIZ = "SAVE_QUIZ";



